<?php

/**
 * @file
 * Contains viewfield_autocomplete.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter() for adding js.
 */
function viewfield_autocomplete_form_node_form_alter(&$form, FormStateInterface $form_state) {
  $form['#attached']['library'][] = 'viewfield_autocomplete/autocomplete_js';
  $node = $form_state->getFormObject()->getEntity();  
  if ($node->getType() == 'blog_detail' || $node->getType() == 'article') {
    // Product Terms.
    $p_vid = 'product';
    $p_terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($p_vid);
    $term_product = [];
    if (!empty($p_terms)) {
      foreach ($p_terms as $term) {
       $term_product[] = $term->name;
      }
      $form['#attached']['drupalSettings']['viewfield_autocomplete']['product'] = $term_product;
    }

    // Solution Terms.
    $s_vid = 'solution';
    $s_terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($s_vid);
    $term_solution = [];
    if (!empty($s_terms)) {
      foreach ($s_terms as $term) {
       $term_solution[] = $term->name;
      }
      $form['#attached']['drupalSettings']['viewfield_autocomplete']['solution'] = $term_solution;
    }

    // Blog Terms.
    $b_vid = 'blog';
    $b_terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($b_vid);
    $term_blog = [];
    if (!empty($b_terms)) {
      foreach ($b_terms as $term) {
       $term_blog[] = $term->name;
      }
      $form['#attached']['drupalSettings']['viewfield_autocomplete']['blog'] = $term_blog;
    }

  }
  else {
    // Product Terms.
    $p_vid = 'product';
    $p_terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($p_vid);
    $term_product = [];
    if (!empty($p_terms)) {
      foreach ($p_terms as $term) {
       $term_product[] = $term->name;
      }
      $form['#attached']['drupalSettings']['viewfield_autocomplete']['product'] = $term_product;
    }

    // Solution Terms.
    $s_vid = 'solution';
    $s_terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($s_vid);
    $term_solution = [];
    if (!empty($s_terms)) {
      foreach ($s_terms as $term) {
       $term_solution[] = $term->name;
      }
      $form['#attached']['drupalSettings']['viewfield_autocomplete']['solution'] = $term_solution;
    }
  }
}
