entity_type_groups:
  node:
    article:
      basic: basic
      advanced: advanced
      open_graph: open_graph
    blog_detail:
      basic: basic
      advanced: advanced
      open_graph: open_graph
    generic_landing:
      basic: basic
      advanced: advanced
      open_graph: open_graph
    homepage:
      basic: basic
      advanced: advanced
      open_graph: open_graph
    page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
    product_detail:
      basic: basic
      advanced: advanced
      open_graph: open_graph
    product_listing:
      basic: basic
      advanced: advanced
      open_graph: open_graph
    product_showcase:
      basic: basic
      advanced: advanced
      open_graph: open_graph
