attributes:
  class:
    label: ''
    description: ''
  target:
    label: ''
    description: ''
    options:
      _blank: 'New window (_blank)'
      _self: 'Same window (_self)'
  container_class:
    label: 'Wrapper Class'
    description: 'Enter value for wrapping <code>class</code> attribute.'
