path: favicons
tags:
  - '<link rel="apple-touch-icon" sizes="180x180" href="http://dev-veeder.pantheonsite.io/sites/default/files/favicons/apple-touch-icon.png">'
  - '<link rel="icon" type="image/png" sizes="32x32" href="http://dev-veeder.pantheonsite.io/sites/default/files/favicons/favicon-32x32.png">'
  - '<link rel="icon" type="image/png" sizes="16x16" href="http://dev-veeder.pantheonsite.io/sites/default/files/favicons/favicon-16x16.png">'
  - '<link rel="manifest" href="http://dev-veeder.pantheonsite.io/sites/default/files/favicons/site.webmanifest">'
  - '<link rel="mask-icon" href="http://dev-veeder.pantheonsite.io/sites/default/files/favicons/safari-pinned-tab.svg" color="#b7b9bc">'
  - '<link rel="shortcut icon" href="http://dev-veeder.pantheonsite.io/sites/default/files/favicons/favicon.ico">'
  - '<meta name="msapplication-TileColor" content="#ffffff">'
  - '<meta name="msapplication-config" content="http://dev-veeder.pantheonsite.io/sites/default/files/favicons/browserconfig.xml">'
  - '<meta name="theme-color" content="#ffffff">'
remove_default: 1
_core:
  default_config_hash: HwbPAleld8fGYWEBocmgnJpHIFH5k4-fdA0eRR2nMKU
